name: Test

on:
  push:
    branches: [ "main" ]
    tags: ["v*.*.*"]
  pull_request:
    branches: [ "main" ]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - uses: actions/setup-python@v7
      with:
        python-version: "3.13"

    - name: Setup environment
      run: |
        pip install uv
        uv sync --all-groups
    - name: Test
      run: |
        uv run just test
